### ISSUE TITLE
Rename vsphere-csi-controller to the default name.

### ISSUE THREAD

**Issue by asta1992** [vsphere-tmm/helm-charts#10]
The Velero Plugin "velero-plugin-for-vsphere" uses static name checks in the cluster to determine the Cluster Flavor ("Vanilla, Tanzu).
But at the moment with this helm chart, the controllers name is "vsphere-csi" and not "vsphere-csi-controller"
So the static checks will fail all the time. See some logs samples from the Velero Plugin.
`vSphere CSI controller, vsphere-csi-controller, is required by velero-plugin-for-vsphere. Please make sure the vSphere CSI controller is installed in the cluster`

Is it possible to rename the controller to the official name?

**Comment by mylesagray** [comment]
@asta1992 What version of the chart are you using? The current (heavily revised) version shows the correct name in place:

https://github.com/vsphere-tmm/helm-charts/blob/master/charts/vsphere-csi/templates/controller/deployment.yaml#L179

**Comment by asta1992** [comment]
I'm using the latest one.
Sorry, I meant the deployment name must be "vsphere-csi-controller"
The Container itself is named correctly.

Check the newest release of the velero-plugin-for-vsphere.
This is a PR which is merged and released:
https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/348

**Comment by mylesagray** [comment]
You could use `fullnameOverride` though I agree, it should work OOTB.

@MaxRink do you have any thoughts on `common.names.fullname` being statically named to `vsphere-csi-controller` with a possibility to override if the user wishes? Is there some guarantee of uniqueness when using `common.names.fullname` were we to statically define it but allow override? For ex. during upgrade?

**Comment by MaxRink** [comment]
@mylesagray yes
https://github.com/bitnami/charts/tree/master/bitnami/common#names
its always generated from the release name, so its uique per HR
It should not matter here tho, as you propably wont run multiple csi instances per cluster

**Comment by MaxRink** [comment]
@asta1992 https://github.com/vsphere-tmm/helm-charts/pull/15 should fix it, there is now a name: filed on both the controller and nodeDS, that allow setting explicit names.
