### ISSUE TITLE
Installing 'vanilla' CPI Fails to start components

### ISSUE THREAD

**Issue by gigs2go** [vsphere-tmm/helm-charts#34]
I've installed the CPI chart :
[talos@k8s-controller-dev-1 ~]$ helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
vsphere-cpi     kube-system     1               2022-04-12 16:29:32.960777084 +0100 BST deployed        vsphere-cpi-1.2.1       v1.22.5

However the logs show :
W0412 15:45:21.265799       1 requestheader_controller.go:193] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:vsphere-cpi" cannot get resource "configmaps" in API group "" in the namespace "kube-system"

I used this cpi-values.yaml file :
config:
  enabled: true
  vcenter:
    vcsa.sysmech.net:
      server: 10.0.0.246
      user: my_user
      password: my_password
      datacenters:
        - HA

Is there a property I can set to fix this problem pls?

**Comment by hasanhakkaev** [comment]
Hi @gigs2go!

The #40 was merged and this should fix your issue.
