### ISSUE TITLE
Fix the secret name of the 'snapshot-validation-webhook' deployment

### ISSUE THREAD

**Issue by thectrltab** [vsphere-tmm/helm-charts#35]
Hi @MaxRink in this commit https://github.com/vsphere-tmm/helm-charts/commit/1f39dc03f47834739d3839b2ddff106e40148752 I think you should have also fix the Secret name here:

https://github.com/vsphere-tmm/helm-charts/blob/296619a452f71c894a27a1ebaa865171f2fcdf07/charts/vsphere-csi/templates/snapshot-validation-webhook/deployment.yaml#L124

---

If I'm not mistaken you should also fix the `app.kubernetes.io/component` tag:

https://github.com/vsphere-tmm/helm-charts/blob/master/charts/vsphere-csi/templates/snapshot-validation-webhook/validatingwebhookconfiguration.yaml#L14

https://github.com/vsphere-tmm/helm-charts/blob/master/charts/vsphere-csi/templates/snapshot-validation-webhook/validatingwebhookconfiguration.yaml#L40

The correct thing would be perhaps to use this value `{{ template "vsphere-csi.snapshotwebhookName" . }}` as in:

https://github.com/vsphere-tmm/helm-charts/blob/master/charts/vsphere-csi/templates/snapshot-validation-webhook/deployment.yaml#L8

**Comment by sathieu** [comment]
Fixed by 5379bed5a79c72cb24dd70687c02edd644312185.

Also 1c704791d2fc0657a3c5f1a27ea2e1faa9ef27c3 fixed the `app.kubernetes.io/component` tag, line 14 but not line 40.

Anyway, the whole snapshot webhook is removed in #48.
