### ISSUE TITLE
Bump 'driver' and 'syncer' image from v2.5.0 to v2.5.1

### ISSUE THREAD

**Issue by thectrltab** [vsphere-tmm/helm-charts#36]
It may be interesting to upload the version of these images:
 - `gcr.io/cloud-provider-vsphere/csi/release/driver:v2.5.1`
 - `gcr.io/cloud-provider-vsphere/csi/release/syncer:v2.5.1`

Related to:
- Issues:
  - https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/1629
- Pulls: 
  - https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1637
  - https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1662
- Release: https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.5.1

**Comment by MaxRink** [comment]
Thats done now, with chart version 2.1.1
