### ISSUE TITLE
snapshot webhook conflict / refactor

### ISSUE THREAD

**Issue by kfox1111** [vsphere-tmm/helm-charts#47]
This chart seems to have its own definitions for the webhook. But there is a semiofficial upstream chart for both the webhook and the controller. Would it be better to remove the existing webhook support instead of fixing it and then conditionally including the webhook and the controller? Then it would be easy to enable/disable the built in support if you also have another driver installed in parallel. It would also be less effort to maintain the chart.

Repo:
https://piraeus.io/helm-charts/

For example:
  chart: piraeus-charts/snapshot-controller
  version: 1.2.1
  chart: piraeus-charts/snapshot-validation-webhook
  version: 1.2.1

**Comment by sathieu** [comment]
Can be closed, now that #48 is merged.
