### ISSUE TITLE
Add reclaimPolicy in the storageclass.yaml template

### ISSUE THREAD

**Issue by cdtzabra** [vsphere-tmm/helm-charts#67]
Hello

can you add the `reclaimPolicy` in the storageclass tempate: https://github.com/vsphere-tmm/helm-charts/blob/master/charts/vsphere-csi/templates/storageclass.yaml ?

User should be able to choose Retain or Delete when storageclass is enabled

See the odc example: https://docs.openshift.com/container-platform/4.9/storage/container_storage_interface/persistent-storage-csi-vsphere.html#persistent-storage-csi-vsphere-stor-policy_persistent-storage-csi-vsphere

Currently as a workaround, I have to create the storageclass separetely  by myself   while the chart could do it directly

**Comment by MaxRink** [comment]
https://github.com/vsphere-tmm/helm-charts/pull/72 should add it
