### ISSUE TITLE
Allow special characters in vcenter password

### ISSUE THREAD

**Issue by arno-pons** [vsphere-tmm/helm-charts#76]
VCenter password with special characters (',*,",...) seems unsupported by the helm chart.
In order to fix it, I had to surround password with double quotes in the vcenter conf secret file generated.

Here is a pull request including a fix for this issue by adding double quotes arround each vcenter configuration values in this secret files, as documented by vmware in the [deploy CSI procedure](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-0AB6E692-AA47-4B6A-8CEA-38B754E16567.html): https://github.com/vsphere-tmm/helm-charts/pull/75

**Comment by PierrePIRONIN** [comment]
Hello there,
Any news on that issue ? It would be nice to see it fixed 😃

**Comment by MaxRink** [comment]
Just merged #75 which should fix it
