### ISSUE TITLE
Update vsphere-csi-driver to 3.2.0 and add topology-aware-file-volume config flag

### ISSUE THREAD

**Issue by QueerCodingGirl** [vsphere-tmm/helm-charts#81]
New 3.2.0 release of the driver:
https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v3.2.0

topology-aware-file-volume config flag:
https://github.com/kubernetes-sigs/vsphere-csi-driver/commit/23e305e3dcd2f29f33de779acd455cc017b05c7b

**Comment by MaxRink** [comment]
The topology config isnt set in upstream so i left it out, too but and you can just inject it via your helm values
